package com.github.bzsy.fishbowl.sqlite.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "AIR_TEMPERATURE_ENTITY".
 */
public class AirTemperatureEntity {

    private Long id;
    private long time;
    private Float temperature;
    private Float heat_index;
    private Integer device_id;

    public AirTemperatureEntity() {
    }

    public AirTemperatureEntity(Long id) {
        this.id = id;
    }

    public AirTemperatureEntity(Long id, long time, Float temperature, Float heat_index, Integer device_id) {
        this.id = id;
        this.time = time;
        this.temperature = temperature;
        this.heat_index = heat_index;
        this.device_id = device_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    public Float getTemperature() {
        return temperature;
    }

    public void setTemperature(Float temperature) {
        this.temperature = temperature;
    }

    public Float getHeat_index() {
        return heat_index;
    }

    public void setHeat_index(Float heat_index) {
        this.heat_index = heat_index;
    }

    public Integer getDevice_id() {
        return device_id;
    }

    public void setDevice_id(Integer device_id) {
        this.device_id = device_id;
    }

}
