package com.github.bzsy.fishbowl.sqlite.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "IMAGE_ENTITY".
 */
public class ImageEntity {

    private Long id;
    private long time;
    private String image_url;
    private String thumbnail_url;
    private Integer device_id;

    public ImageEntity() {
    }

    public ImageEntity(Long id) {
        this.id = id;
    }

    public ImageEntity(Long id, long time, String image_url, String thumbnail_url, Integer device_id) {
        this.id = id;
        this.time = time;
        this.image_url = image_url;
        this.thumbnail_url = thumbnail_url;
        this.device_id = device_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

    public String getThumbnail_url() {
        return thumbnail_url;
    }

    public void setThumbnail_url(String thumbnail_url) {
        this.thumbnail_url = thumbnail_url;
    }

    public Integer getDevice_id() {
        return device_id;
    }

    public void setDevice_id(Integer device_id) {
        this.device_id = device_id;
    }

}
