package com.github.bzsy.fishbowl.sqlite.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LIGHT_ENTITY".
 */
public class LightEntity {

    private Long id;
    private long time;
    private Integer light;
    private Integer device_id;

    public LightEntity() {
    }

    public LightEntity(Long id) {
        this.id = id;
    }

    public LightEntity(Long id, long time, Integer light, Integer device_id) {
        this.id = id;
        this.time = time;
        this.light = light;
        this.device_id = device_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    public Integer getLight() {
        return light;
    }

    public void setLight(Integer light) {
        this.light = light;
    }

    public Integer getDevice_id() {
        return device_id;
    }

    public void setDevice_id(Integer device_id) {
        this.device_id = device_id;
    }

}
